config/routes.rb
Rails.application.routes.draw do
  resources :students do
    collection do
      get :posters
      get :stories
      get :researchs
      get :clubs
    end
  end

  resources :requirements do
    collection do
      get :computer_science
      get :data_science_analytics
    end
  end

  resources :courses

  resources :faculties

  root "department#index"
  get "department/about"
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
    def index
    end
  
    def about
    end
  end

app/views/department/_footer.html.erb
<div class="container">
  <footer class="py-3 my-2">
    <p class="text-center text-muted">Copyright &copy; 2022 CS Department</p>
  </footer>
</div>

app/views/department/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "CS Department", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "About Department", department_about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/department/about.html.erb
<div class="container">
    <h1>About Department</h1>
<div>

app/views/department/index.html.erb
<%= stylesheet_link_tag "department" %>
<div class="container overflow-hidden">
  <div class="container text-center">
    <div class="row header">
      <div class="col">
        <h3 class="display-5">Beloit Computer Science Program</h3>
      </div>
    </div>
    <div class="row row-cols-2 row-cols-md-2 px-4">
      <%= link_to students_path, class:"nav-link col btn btn-light center-div" do %>
        <div class="card" >
          <%= image_tag "/assets/bg/story-bg.jpg", class: "card-img-top" %>
          <div class="text-centered">Student Stories & Research</div>
        </div>
      <% end %>
      <%= link_to faculties_path, class:"nav-link col btn btn-light center-div" do %>
        <div class="card" >
          <%= image_tag "/assets/bg/dept-bg.jpg", class: "card-img-top" %>
          <div class="text-centered">Faculty & Staff</div>
        </div>
      <% end %>
      <%= link_to courses_path, class:"nav-link col btn btn-light center-div" do %>
        <div class="card" >
          <%= image_tag "/assets/bg/course-bg.jpg", class: "card-img-top" %>
          <div class="text-centered">Courses</div>
        </div>
      <% end %>
      <%= link_to requirements_path, class:"nav-link col btn btn-light center-div" do %>
        <div class="card" >
          <%= image_tag "/assets/bg/requirement-bg.jpg", class: "card-img-top" %>
          <div class="text-centered">Computer Science & <br>
             Data Science <br>
            Major & Minor Requirements</div>
        </div>
      <% end %>
    </div>
  </div>
</div>