config/routes.rb
Rails.application.routes.draw do
  resources :students do
    collection do
      get :posters
      get :stories
      get :researchs
      get :clubs
    end
  end

  resources :requirements do
    collection do
      get :computer_science
      get :data_science_analytics
    end
  end

  resources :courses

  resources :faculties

  root "department#index"
  get "department/about"
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/students_controller.rb
require "csv"

class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html do
          redirect_to student_url(@student),
                      notice: "Student was successfully created."
        end
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @student.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html do
          redirect_to student_url(@student),
                      notice: "Student was successfully updated."
        end
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @student.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html do
        redirect_to students_url, notice: "Student was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def posters
    @posters = CSV.read("app/assets/data/poster.csv", headers: true)
  end

  def stories
  end

  def researchs
    @researchs = CSV.read("app/assets/data/research.csv", headers: true)
  end

  def clubs
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:title, :description, :image, :introduction)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :introduction, style: "display: block" %>
    <%= form.text_field :introduction %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">

    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
            <%= link_to "Students stories & Research", students_path %>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            <%= student.name %>
        </li>
        </ol>
    </nav>

    <h1>
        <%= student.title %>
    </h1>
    <hr>
    <h4>
        <%= student.introduction %>
    </h4>
    <%= image_tag (student.image), class: "rounded", style: "max-width: 200px; margin: 2rem 0"%>
    <p>
        <%= student.description %>
    </p>

</div>

app/views/students/clubs.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
            <%= link_to "Student Stories & Research", students_path %>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Clubs
        </li>
    </ol>
</nav>

<h1>Clubs</h1>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<%= stylesheet_link_tag "student" %>
<p style="color: green"><%= notice %></p>
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">Students stories & Research</li>
  </ol>
</nav>
<h1>Student Stories & Research</h1>
<div class="container text-center overflow-hidden">
  <div class="row row-cols-2 row-cols-md-2 px-4">
    <%= link_to stories_students_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/alumni-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">Student & Alumni Stories</div>
      </div>
    <% end %>
    <%= link_to researchs_students_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/research-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">Ongoing Researchs</div>
      </div>
    <% end %>
    <%= link_to posters_students_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/poster-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">Posters</div>
      </div>
    <% end %>
    <%= link_to clubs_students_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/cs-club-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">CS Club</div>
      </div>
    <% end %>
  </div>
</div>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/posters.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Student Stories & Research", students_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Posters
    </li>
  </ol>
</nav>
<h1>Posters</h1>
<div id="students-poster">
  <div class="row row-cols-3 row-cols-md-3 g-4">
    <% @posters.each do |row| %>
      <div class="col">
        <div class="card" >
          <%= image_tag (row["poster"]), class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title">
              <%= row["name"] %>
            </h5>
            <p class="card-text">
              <%= row["description"] %>
            </p>
            <p class="card-text">
              <small><%= row["date"] %></small>
            </p>
            <%= link_to "View full poster", row["poster"], class: "btn btn-primary", target: :_blank %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/students/researchs.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Student Stories & Research", students_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Researchs
    </li>
  </ol>
</nav>
<h1>Research</h1>
<div class="d-grid gap-4" id="students-research">
  <% @researchs.each do |row| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <%= row["title"] %>
        </h5>
        <p class="card-text"><small class="text-muted">
            <%= row["name"] %>
          </small></p>
        <p class="card-text">
          <%= row["description"] %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/students/stories.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
            <%= link_to "Student Stories & Research", students_path %>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Student & Alumni Stories
        </li>
    </ol>
</nav>

<h1>Student & Alumni Stories</h1>