config/routes.rb
Rails.application.routes.draw do
  resources :students do
    collection do
      get :posters
      get :stories
      get :researchs
      get :clubs
    end
  end

  resources :requirements do
    collection do
      get :computer_science
      get :data_science_analytics
    end
  end

  resources :courses

  resources :faculties

  root "department#index"
  get "department/about"
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: %i[ show edit update destroy ]

  # GET /faculties or /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1 or /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties or /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to faculty_url(@faculty), notice: "Faculty was successfully created." }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1 or /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to faculty_url(@faculty), notice: "Faculty was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1 or /faculties/1.json
  def destroy
    @faculty.destroy

    respond_to do |format|
      format.html { redirect_to faculties_url, notice: "Faculty was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faculty_params
      params.require(:faculty).permit(:first_name, :last_name, :title, :pronouns, :email, :phone, :office, :link)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_faculty.html.erb
<div id="<%= dom_id faculty %>">

  <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Home", root_path %>
      </li>
      <li class="breadcrumb-item">
        <%= link_to "Faculty & Staff", faculties_path %>
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        <%= "#{faculty.first_name} #{faculty.last_name}" %>
      </li>
    </ol>
  </nav>

  <h1>
    <%= "#{faculty.first_name} #{faculty.last_name}" %>
  </h1>

  <p style="margin-bottom: 2.5rem">
    <%= faculty.title %>
  </p>

  <div>
    <%= image_tag (faculty.link), class: "img-responsive"%>
  </div>

  <p>
    <strong>Pronouns:</strong>
    <%= faculty.pronouns %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= faculty.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= faculty.phone %>
  </p>

  <p>
    <strong>Office:</strong>
    <%= faculty.office %>
  </p>

</div>

app/views/faculties/_form.html.erb
<%= form_with(model: faculty) do |form| %>
  <% if faculty.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
        <% faculty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :pronouns, style: "display: block" %>
    <%= form.text_field :pronouns %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :office, style: "display: block" %>
    <%= form.text_field :office %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing faculty</h1>

<%= render "form", faculty: @faculty %>

<br>

<div>
  <%= link_to "Show this faculty", @faculty %> |
  <%= link_to "Back to faculties", faculties_path %>
</div>

app/views/faculties/index.html.erb
<p style="color: green"><%= notice %></p>

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">Faculty & Staff</li>
  </ol>
</nav>

<h1>Faculty & Staff</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Office</th>
    </tr>
  </thead>
  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= link_to faculty.first_name + ' ' + faculty.last_name, faculty %></td>
        <td><%= faculty.email %></td>
        <td><%= faculty.phone %></td>
        <td><%= faculty.office %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# <%= link_to "New faculty", new_faculty_path %>
<%# http://127.0.0.1:3000/faculties/new %>

app/views/faculties/new.html.erb
<h1>New faculty</h1>

<%= render "form", faculty: @faculty %>

<br>

<div>
  <%= link_to "Back to faculties", faculties_path %>
</div>

app/views/faculties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @faculty %>

<%# <div> %>
  <%# <%= link_to "Edit this faculty", edit_faculty_path(@faculty) %>
  <%# <%= link_to "Back to faculties", faculties_path %>

  <%# <%= button_to "Destroy this faculty", @faculty, method: :delete %>
<%# </div> %>