config/routes.rb
Rails.application.routes.draw do
  resources :students do
    collection do
      get :posters
      get :stories
      get :researchs
      get :clubs
    end
  end

  resources :requirements do
    collection do
      get :computer_science
      get :data_science_analytics
    end
  end

  resources :courses

  resources :faculties

  root "department#index"
  get "department/about"
end

app/models/requirement.rb
class Requirement < ApplicationRecord
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: %i[ show edit update destroy ]

  # GET /requirements or /requirements.json
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1 or /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements or /requirements.json
  def create
    @requirement = Requirement.new(requirement_params)

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to requirement_url(@requirement), notice: "Requirement was successfully created." }
        format.json { render :show, status: :created, location: @requirement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1 or /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to requirement_url(@requirement), notice: "Requirement was successfully updated." }
        format.json { render :show, status: :ok, location: @requirement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1 or /requirements/1.json
  def destroy
    @requirement.destroy

    respond_to do |format|
      format.html { redirect_to requirements_url, notice: "Requirement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def computer_science
  end

  def data_science_analytics
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def requirement_params
      params.fetch(:requirement, {})
    end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/requirements/_form.html.erb
<%= form_with(model: requirement) do |form| %>
  <% if requirement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
        <% requirement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/requirements/_requirement.html.erb
<div id="<%= dom_id requirement %>">
</div>

app/views/requirements/computer_science.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <%= link_to "Home", root_path %>
        </li>
        <li class="breadcrumb-item">
            <%= link_to "Computer Science & Data Science Major & Minor Requirements", requirements_path %>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
            Computer Science Requirements
        </li>
    </ol>
</nav>

<h1>Computer Science Requirements</h1>

<p>
Computer science focuses on how to create a model for a real-world situation,
how to represent that model inside a computer, and how to devise mechanizable techniques
to manipulate that model. Such models and techniques are used to understand or investigate the situation or to solve real-world problems.
</p>

<p>
Introductory courses prepare a student to do such problem-solving in any domain.
Students pursuing a computer science major learn more advanced techniques for such modeling and
also focus on models specific to computer science and computer technology. Upper-level elective
courses prepare students for graduate-level study and for vocations in various computer fields.
</p>

<div class="accordion" id="CsciRequirement" style="margin: 2rem 0;">

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingCsciMajor">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCsciMajor" aria-expanded="false" aria-controls="collapseCsciMajor">
        <strong>Major Requirements (11.5 units)</strong>
      </button>
    </h2>
    <div id="collapseCsciMajor" class="accordion-collapse collapse show" aria-labelledby="headingCsciMajor" data-bs-parent="#CsciRequirement">
      <div class="accordion-body">
        <ol>
          <li style="margin-bottom: 1rem"><strong>Eight</strong> and <strong>half</strong> departmental units: CSCI
            <%= link_to "111", course_path(id: 3)%>,
            <%= link_to "175", course_path(id: 6)%>,
            <%= link_to "204", course_path(id: 7)%>,
            <%= link_to "245", course_path(id: 8)%>,
            <%= link_to "315", course_path(id: 11)%>,
            <%= link_to "335", course_path(id: 12)%>,
            <%= link_to "347", course_path(id: 13)%> (.5),
            <%= link_to "367", course_path(id: 14)%>, and
            <%= link_to "377", course_path(id: 16)%>.
          </li>
          <li style="margin-bottom: 1rem"><strong>One</strong> elective, approved by the advisor that incorporates computer science skills into another discipline, such as but not limited to COGS 280, DSDA 345 and 385, and MATH 300.</li>
          <li style="margin-bottom: 1rem"><strong>Two</strong> supporting units: MATH 110 or 113, and 160.</li>
          <li style="margin-bottom: 1rem">Students planning to attend graduate school in computer science should consult with an advisor for additional study that should be done. The computer science program recognizes the importance of oral and written communication.</li>
          <li style="margin-bottom: 1rem">Successful graduates of the program should be able to speak and write effectively in order to communicate important ideas to diverse audiences. The program helps students develop these capabilities in the context of computer science through the progression in its courses. In written communication, students are expected to document their programming work via both internal and external documentation. In oral communication, students are expected to present all aspects of their work and effectively communicate in teams. In all forms of communication, students are expected to be able to address both technical and general audiences. The capstone experiences offer an important opportunity to solidify and extend these skills as students prepare for their future work.</li>
          <li style="margin-bottom: 1rem">Students majoring computer science may choose to receive the Bachelor of Science degree rather than the Bachelor of Arts degree by completing a minimum of 4 units in biology, chemistry, geology, and/or physics.</li>
        </ol>
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header" id="headingCsciMinor">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCsciMinor" aria-expanded="false" aria-controls="collapseCsciMinor">
        <strong>Minor Requirements (6 units)</strong>
      </button>
    </h2>
    <div id="collapseCsciMinor" class="accordion-collapse collapse" aria-labelledby="headingCsciMinor" data-bs-parent="#CsciRequirement">
      <div class="accordion-body">
        <ol>
          <li style="margin-bottom: 1rem"><strong>Two</strong> units of core courses: CSCI
            <%= link_to "111", course_path(id: 3)%>, and
            <%= link_to "204", course_path(id: 7)%>.
          </li>
          <li style="margin-bottom: 1rem"><strong>Four</strong> additional units of computer science courses chosen from
          <%= link_to "175", course_path(id: 6)%>,
          <%= link_to "245", course_path(id: 8)%>,
          <%= link_to "315", course_path(id: 11)%>,
          <%= link_to "335", course_path(id: 12)%>,
          <%= link_to "347", course_path(id: 13)%>,
          <%= link_to "367", course_path(id: 14)%>, and
          <%= link_to "377", course_path(id: 16)%>. COGS 280, DSDA 345, 385, or MATH 300 may be used toward this 1 unit if approved in advance by a computer science advisor or another course approved in advance by the department chair.</li>
        </ol>
      </div>
    </div>
  </div>

</div>

app/views/requirements/data_science_analytics.html.erb
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to "Computer Science & Data Science Major & Minor Requirements", requirements_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      Data Science & Analytics Requirements
    </li>
  </ol>
</nav>
<h1>Data Science & Analytics Requirements</h1>
<p>
  For both data science and data analytics majors, students take:
  <ol>
    <li><strong>Core courses</strong> in math, statistics, computer science.</li>
    <li>
      <strong>Disciplinary specialty:</strong> students choose one discipline (from among economics, psychology, political science, sociology, anthropology, education studies, biology, chemistry, geology)
      and take a sequence of 3-5 courses that teach students disciplinary thinking and how data is used in that discipline.
    </li>
    <li>Courses from the humanities on data work.</li>
    <li>One sophomore seminar that introduces students to the data science and data analytics major and career.</li>
    <li>One senior seminar or capstone experience, in which students work on a real data project.</li>
  </ol>
</p>
<p>
  Majoring in data science or data analytics at Beloit, you will learn not only how to work with data, but also the humanistic foundation of data work.
  You will acquire career-ready skills that will position you, at graduation, to work in a variety of fields that make use of complex data sets (e.g. business, the arts, science, government, and more).
</p>
<div class="accordion" id="DsdaRequirement" style="margin: 2rem 0;">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingDsdaMajor">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDsdaMajor" aria-expanded="false" aria-controls="collapseDsdaMajor">
        <strong>Data Science Major (15 units)</strong>
      </button>
    </h2>
    <div id="collapseDsdaMajor" class="accordion-collapse collapse show" aria-labelledby="headingDsdaMajor" data-bs-parent="#DsdaRequirement">
      <div class="accordion-body">
        <ol>
          <li style="margin-bottom: 1rem">DSDA 210 (.5), 345, and 385.</li>
          <li style="margin-bottom: 1rem"><strong>Four</strong> units in Mathematics: MATH 110, 115, 175, and 205.</li>
          <li style="margin-bottom: 1rem"><strong>Three</strong> Three units in Computer science: CSCI
            <%= link_to "111", course_path(id: 3)%>,
            <%= link_to "204", course_path(id: 7)%>, and
            <%= link_to "367", course_path(id: 14)%>.
          </li>
          <li style="margin-bottom: 1rem"><strong>Two</strong> units in Data Science and Data Analytics or the humanities, chosen from ART 325, DSDA 215, ENGL 265, GLAM 249, MDST 150, CPLT 215.</li>
          <li style="margin-bottom: 1rem"><strong>One</strong> disciplinary specialty chosen from the following (3 units):
            <ol>
              <li><strong>Anthropology:</strong> Two units chosen from any 100-level anthropology courses and 240 (201 and 225 are recommended).</li>
              <li><strong>Biology:</strong> one 100-level biology course and 247; either 215 or 372.</li>
              <li><strong>Chemistry:</strong> 117 and 220, and one chosen from 225, 240, 245, or 300.</li>
              <li><strong>Economics:</strong> 199, 211, 251 (one from 271, 302, or 303 is recommended).</li>
              <li><strong>Education and Youth Studies:</strong> 201, 252, and 306.</li>
              <li><strong>Environmental Studies:</strong> one laboratory science course, one statistics or quantitative course from any discipline, and Environmental Studies 258.</li>
              <li><strong>Geology:</strong> 100 or 110; one statistics or quantitative course from any discipline; one chosen from Geology 230, 235, or 245, or Environmental Studies 258, with a geology project.</li>
              <li><strong>Health and Society:</strong> 140, one statistics or quantitative course from any discipline, and Biology 215.</li>
              <li><strong>Physics:</strong> 101 and 335; either 210 or 345.</li>
              <li><strong>Political Science:</strong> 110 and 201; either 207 or 215.</li>
              <li><strong>Psychology:</strong> 100, 161, 162.</li>
              <li><strong>Sociology:</strong> either 100 or 150; 205 and 211.</li>
            </ol>
          </li>
          <li style="margin-bottom: 1rem">DSDA 310 (.5).</li>
        </ol>
        If students majoring in data science or data analytics want to major or minor in another discipline, up to four units are allowed to be double counted.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingDsdaMinor">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDsdaMinor" aria-expanded="false" aria-controls="collapseDsdaMinor">
        <strong>Data Analytics Major (6 units)</strong>
      </button>
    </h2>
    <div id="collapseDsdaMinor" class="accordion-collapse collapse" aria-labelledby="headingDsdaMinor" data-bs-parent="#DsdaRequirement">
      <div class="accordion-body">
        <ol>
          <li style="margin-bottom: 1rem">DSDA 210 (.5)</li>
          <li style="margin-bottom: 1rem"><strong>One</strong> unit in Mathematics: MATH 110.</li>
          <li style="margin-bottom: 1rem"><strong>Three</strong> Three units in Computer science: CSCI
            <%= link_to "111", course_path(id: 3)%>,
            <%= link_to "204", course_path(id: 7)%>, and
            <%= link_to "367", course_path(id: 14)%>.
          </li>
          <li style="margin-bottom: 1rem"><strong>Three</strong> units in Data Science and Data Analytics or the humanities, chosen from ART 325, DSDA 215, ENGL 265, GLAM 249, MDST 150, CPLT 215.</li>
          <li style="margin-bottom: 1rem"><strong>One</strong> disciplinary specialty chosen from the following (3 units, unless otherwise indicated):</li>
          <li style="margin-bottom: 1rem"><strong>One</strong> disciplinary specialty chosen from the following (3 units):
            <ol>
              <li><strong>Anthropology:</strong> Two units chosen from any 100-level anthropology courses and 240 (201 and 225 are recommended).</li>
              <li><strong>Biology:</strong> one 100-level biology course and 247; either 215 or 372.</li>
              <li><strong>Chemistry:</strong> 117 and 220, and one chosen from 225, 240, 245, or 300.</li>
              <li><strong>Economics:</strong> 199, 211, 251 (one from 271, 302, or 303 is recommended).</li>
              <li><strong>Education and Youth Studies:</strong> 201, 252, and 306.</li>
              <li><strong>Environmental Studies:</strong> one laboratory science course, one statistics or quantitative course from any discipline, and Environmental Studies 258.</li>
              <li><strong>Geology:</strong> 100 or 110; one statistics or quantitative course from any discipline; one chosen from Geology 230, 235, or 245, or Environmental Studies 258, with a geology project.</li>
              <li><strong>Health and Society:</strong> 140, one statistics or quantitative course from any discipline, and Biology 215.</li>
              <li><strong>Physics:</strong> 101 and 335; either 210 or 345.</li>
              <li><strong>Political Science:</strong> 110 and 201; either 207 or 215.</li>
              <li><strong>Psychology:</strong> 100, 161, 162.</li>
              <li><strong>Sociology:</strong> either 100 or 150; 205 and 211.</li>
            </ol>
          </li>
          <li style="margin-bottom: 1rem">DSDA 310 (.5).</li>
        </ol>
        If students majoring in data science or data analytics want to major or minor in another discipline, up to four units are allowed to be double counted.
      </div>
    </div>
  </div>
</div>

app/views/requirements/edit.html.erb
<h1>Editing requirement</h1>

<%= render "form", requirement: @requirement %>

<br>

<div>
  <%= link_to "Show this requirement", @requirement %> |
  <%= link_to "Back to requirements", requirements_path %>
</div>

app/views/requirements/index.html.erb
<%= stylesheet_link_tag "requirement" %>
<p style="color: green"><%= notice %></p>
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Home", root_path %>
    </li>
    <li class="breadcrumb-item active" aria-current="page">Computer Science & Data Science Major & Minor Requirements</li>
  </ol>
</nav>
<h1>Computer Science & Data Science Major & Minor Requirements</h1>
<div class="container text-center overflow-hidden">
  <div class="row row-cols-2 row-cols-md-2 px-4">
    <%= link_to computer_science_requirements_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/cs-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">Computer Science</div>
      </div>
    <% end %>
    <%= link_to data_science_analytics_requirements_path, class:"nav-link col btn btn-light center-div" do %>
      <div class="card" >
        <%= image_tag "/assets/bg/ds-bg.jpg", class: "card-img-top" %>
        <div class="text-centered">Data Science & Analytics</div>
      </div>
    <% end %>
  </div>
</div>

app/views/requirements/new.html.erb
<h1>New requirement</h1>

<%= render "form", requirement: @requirement %>

<br>

<div>
  <%= link_to "Back to requirements", requirements_path %>
</div>

app/views/requirements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @requirement %>

<div>
  <%= link_to "Edit this requirement", edit_requirement_path(@requirement) %> |
  <%= link_to "Back to requirements", requirements_path %>

  <%= button_to "Destroy this requirement", @requirement, method: :delete %>
</div>